---
# tasks file for roles/microk8s-controllers
- name: get join code
  command: microk8s add-node -l 600
  register: join_code
  changed_when: false
  run_once: true
  when: inventory_hostname == groups["controllers"][0]

- name: Join node into cluster as controller
  command: "{{join_code.stdout| regex_search('(microk8s join \\S+)\\n\\n','\\1') | first}}"
  register: join_output
  changed_when: " not (('is already known' in join_output.stdout) or ('The joining node has the same IP' in join_output.stdout))"
  failed_when: "not (('is already known' in join_output.stdout) or ('The node has joined the cluster' in join_output.stdout) or ('The joining node has the same IP' in join_output.stdout) or ('Waiting for this node to finish joining the cluster' in join_output.stdout))"

- name: enable community addons
  command: "microk8s enable community"
  run_once: true
  register: addon_output
  changed_when: "'is already enabled' not in addon_output.stdout"

- name: enable addons
  run_once: true
  command: "microk8s enable {{item}}"
  loop: "{{microk8s_addons}}"
  register: addon_output
  changed_when: "'is already enabled' not in addon_output.stdout"

